// mobile/src/SettingsPage.tsx
import { useState } from 'react';
import {
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Switch,
  Text,
  TextInput,
  View,
} from 'react-native';
import * as Clipboard from 'expo-clipboard';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { activeCookie, BarPos, getSettings, replaceSettings, saveSettings } from './settings';
import { showSheet } from './components/sheets';
import { toast } from './components/Toast';
import { colors } from './theme';

// Full settings page, ported from the web app: shown by the Settings tab
// (bottom tab bar) as an opaque page over the feed, exactly like the web
// frontend's #settings-page. Multi-account cookie management (masked until
// revealed), display/behavior preferences, post type filters, and settings
// export/import.

export type SettingsResult = { changed: boolean; reloadFeed: boolean };

const BAR_POS_OPTIONS = [
  { text: 'Bottom', value: 'bottom' },
  { text: 'Top', value: 'top' },
  { text: 'Left (vertical)', value: 'left' },
  { text: 'Right (vertical)', value: 'right' },
];

function Row({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <View style={styles.row}>
      <Text style={styles.rowLabel}>{label}</Text>
      {children}
    </View>
  );
}

function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (v: boolean) => void }) {
  return (
    <Row label={label}>
      <Switch
        value={value}
        onValueChange={onChange}
        trackColor={{ true: colors.accent, false: '#33333f' }}
        thumbColor="#fff"
      />
    </Row>
  );
}

export function SettingsPage({ onClose }: { onClose: (result: SettingsResult) => void }) {
  const insets = useSafeAreaInsets();
  const s0 = getSettings();
  const [editingAccount, setEditingAccount] = useState(s0.accounts.length ? s0.activeAccount : -1);
  const [accountName, setAccountName] = useState(
    s0.accounts[s0.activeAccount]?.name ?? ''
  );
  const [cookie, setCookie] = useState('');
  const [cookieRevealed, setCookieRevealed] = useState(!s0.accounts[s0.activeAccount]?.cookie);
  const [serverUrl, setServerUrl] = useState(s0.serverUrl);
  const [imageSeconds, setImageSeconds] = useState(String(s0.imageSeconds));
  const [prefs, setPrefs] = useState({
    fillScreen: s0.fillScreen,
    vertical: s0.vertical,
    showPauseIcon: s0.showPauseIcon,
    barPos: s0.barPos,
    barInvert: s0.barInvert,
    showImages: s0.showImages,
    showVideos: s0.showVideos,
    showText: s0.showText,
    skipSeen: s0.skipSeen,
  });
  const [ioText, setIoText] = useState('');
  const [ioVisible, setIoVisible] = useState(false);

  const storedCookie = (idx: number) => getSettings().accounts[idx]?.cookie ?? '';

  const selectAccount = (idx: number) => {
    setEditingAccount(idx);
    setAccountName(idx >= 0 ? getSettings().accounts[idx]?.name ?? '' : '');
    setCookie('');
    setCookieRevealed(idx < 0 || !storedCookie(idx));
  };

  const pickAccount = async () => {
    const accounts = getSettings().accounts;
    const options = accounts.map((a, i) => ({
      text: a.name + (i === getSettings().activeAccount ? ' (active)' : ''),
      value: String(i),
    }));
    options.push({ text: '+ Add account…', value: 'new' });
    const v = await showSheet('Account', options, editingAccount >= 0 ? String(editingAccount) : 'new');
    if (v === undefined) return;
    selectAccount(v === 'new' ? -1 : Number(v));
  };

  const deleteAccount = () => {
    if (editingAccount < 0) return;
    const s = getSettings();
    const accounts = s.accounts.filter((_, i) => i !== editingAccount);
    let active = s.activeAccount >= accounts.length ? 0 : s.activeAccount;
    saveSettings({ accounts, activeAccount: active });
    selectAccount(accounts.length ? Math.min(editingAccount, accounts.length - 1) : -1);
    toast('Account deleted');
  };

  const revealCookie = () => {
    setCookie(storedCookie(editingAccount));
    setCookieRevealed(true);
  };

  const save = () => {
    const s = getSettings();
    const prevCookie = activeCookie();
    const prevServer = s.serverUrl.trim();
    const filtersChanged =
      prefs.showImages !== s.showImages ||
      prefs.showVideos !== s.showVideos ||
      prefs.showText !== s.showText ||
      prefs.skipSeen !== s.skipSeen;

    // Saving selects the edited account as the active one. A masked cookie
    // field means "unchanged"; once revealed the field is authoritative.
    const accounts = [...s.accounts];
    let active = s.activeAccount;
    const name = accountName.trim();
    const newCookie = cookieRevealed ? cookie.trim() : storedCookie(editingAccount);
    if (editingAccount === -1) {
      if (name || newCookie) {
        accounts.push({ name: name || `Account ${accounts.length + 1}`, cookie: newCookie });
        active = accounts.length - 1;
      }
    } else if (accounts[editingAccount]) {
      accounts[editingAccount] = { name: name || `Account ${editingAccount + 1}`, cookie: newCookie };
      active = editingAccount;
    }

    saveSettings({
      accounts,
      activeAccount: active,
      serverUrl: serverUrl.trim(),
      imageSeconds: Math.max(1, parseFloat(imageSeconds) || 8),
      ...prefs,
    });

    if (!prefs.showImages && !prefs.showVideos && !prefs.showText) {
      toast('All post types disabled — the feed will be empty');
    } else {
      toast('Settings saved', 1500);
    }
    onClose({
      changed: true,
      reloadFeed:
        filtersChanged || activeCookie() !== prevCookie || getSettings().serverUrl.trim() !== prevServer,
    });
  };

  const exportSettings = async () => {
    const json = JSON.stringify(getSettings(), null, 1);
    setIoText(json);
    setIoVisible(true);
    try {
      await Clipboard.setStringAsync(json);
      toast('Settings copied to clipboard');
    } catch {
      toast('Copy the JSON from the box below');
    }
  };

  const importSettings = () => {
    if (!ioVisible || !ioText.trim()) {
      setIoText('');
      setIoVisible(true);
      toast('Paste exported JSON, then press Import again');
      return;
    }
    let parsed: unknown;
    try {
      parsed = JSON.parse(ioText);
    } catch {
      toast('That is not valid JSON');
      return;
    }
    try {
      replaceSettings(parsed);
    } catch (err: any) {
      toast(String(err?.message || err));
      return;
    }
    toast('Settings imported');
    onClose({ changed: true, reloadFeed: true });
  };

  const currentAccountLabel =
    editingAccount >= 0
      ? getSettings().accounts[editingAccount]?.name ?? `Account ${editingAccount + 1}`
      : '+ Add account…';
  const hasMaskedCookie = !cookieRevealed && !!storedCookie(editingAccount);

  return (
    <View style={styles.page}>
      <KeyboardAvoidingView style={styles.fill} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
        <View style={styles.inner}>
          <ScrollView
            keyboardShouldPersistTaps="handled"
            contentContainerStyle={[styles.content, { paddingTop: insets.top + 14 }]}
          >
            <Text style={styles.title}>Settings</Text>

            <Text style={styles.section}>Account</Text>
            <Pressable style={styles.pickerRow} onPress={pickAccount} testID="account-picker">
              <Text style={styles.pickerText}>{currentAccountLabel}</Text>
              <Text style={styles.pickerChevron}>▾</Text>
            </Pressable>
            <Text style={styles.label}>Account name</Text>
            <TextInput
              style={styles.input}
              value={accountName}
              onChangeText={setAccountName}
              placeholder="e.g. main"
              placeholderTextColor={colors.hint}
              autoCapitalize="none"
              autoCorrect={false}
              testID="account-name"
            />
            <Text style={styles.label}>Reddit cookie</Text>
            {hasMaskedCookie ? (
              <View style={styles.maskedRow}>
                <Text style={styles.maskedText}>
                  Cookie saved ({storedCookie(editingAccount).length} chars)
                </Text>
                <Pressable style={styles.smallBtn} onPress={revealCookie} testID="cookie-reveal">
                  <Text style={styles.smallBtnText}>Show</Text>
                </Pressable>
              </View>
            ) : (
              <TextInput
                style={[styles.input, styles.cookieInput]}
                value={cookie}
                onChangeText={setCookie}
                placeholder="Paste the FULL Cookie header from a logged-in reddit.com request (DevTools → Network). Optional for public subreddits."
                placeholderTextColor={colors.hint}
                autoCapitalize="none"
                autoCorrect={false}
                multiline
                testID="cookie"
              />
            )}
            {editingAccount >= 0 ? (
              <Pressable onPress={deleteAccount}>
                <Text style={styles.danger}>Delete this account</Text>
              </Pressable>
            ) : null}

            <Text style={styles.section}>Server</Text>
            <Text style={styles.label}>Server URL</Text>
            <TextInput
              style={styles.input}
              value={serverUrl}
              onChangeText={setServerUrl}
              placeholder={Platform.OS === 'web' ? 'Empty = this server' : 'https://redditview.example.com'}
              placeholderTextColor={colors.hint}
              autoCapitalize="none"
              autoCorrect={false}
              keyboardType="url"
              testID="server-url"
            />

            <Text style={styles.section}>Behavior</Text>
            <Row label="Image duration (seconds)">
              <TextInput
                style={[styles.input, styles.numInput]}
                value={imageSeconds}
                onChangeText={setImageSeconds}
                keyboardType="numeric"
                testID="image-seconds"
              />
            </Row>
            <Toggle label="Fill screen (crop to fill)" value={prefs.fillScreen} onChange={(v) => setPrefs({ ...prefs, fillScreen: v })} />
            <Toggle label="Vertical navigation (swipe up/down)" value={prefs.vertical} onChange={(v) => setPrefs({ ...prefs, vertical: v })} />
            <Toggle label="Paused indicator on videos" value={prefs.showPauseIcon} onChange={(v) => setPrefs({ ...prefs, showPauseIcon: v })} />
            <Row label="Progress bar position">
              <Pressable
                style={styles.smallBtn}
                onPress={async () => {
                  const v = await showSheet('Progress bar position', BAR_POS_OPTIONS, prefs.barPos);
                  if (v !== undefined) setPrefs({ ...prefs, barPos: v as BarPos });
                }}
              >
                <Text style={styles.smallBtnText}>
                  {BAR_POS_OPTIONS.find((o) => o.value === prefs.barPos)?.text} ▾
                </Text>
              </Pressable>
            </Row>
            <Toggle label="Left/right progress bar fills upwards" value={prefs.barInvert} onChange={(v) => setPrefs({ ...prefs, barInvert: v })} />
            <Toggle label="Skip posts you've already seen" value={prefs.skipSeen} onChange={(v) => setPrefs({ ...prefs, skipSeen: v })} />

            <Text style={styles.section}>Show post types</Text>
            <Toggle label="Images & galleries" value={prefs.showImages} onChange={(v) => setPrefs({ ...prefs, showImages: v })} />
            <Toggle label="Videos" value={prefs.showVideos} onChange={(v) => setPrefs({ ...prefs, showVideos: v })} />
            <Toggle label="Text posts" value={prefs.showText} onChange={(v) => setPrefs({ ...prefs, showText: v })} />

            <Text style={styles.section}>Transfer</Text>
            <View style={styles.ioRow}>
              <Pressable style={styles.smallBtn} onPress={exportSettings} testID="export-btn">
                <Text style={styles.smallBtnText}>Export settings</Text>
              </Pressable>
              <Pressable style={styles.smallBtn} onPress={importSettings} testID="import-btn">
                <Text style={styles.smallBtnText}>Import settings</Text>
              </Pressable>
            </View>
            {ioVisible ? (
              <TextInput
                style={[styles.input, styles.cookieInput, styles.mono]}
                value={ioText}
                onChangeText={setIoText}
                multiline
                autoCapitalize="none"
                autoCorrect={false}
                placeholder="Exported settings JSON appears here — or paste JSON and press Import again"
                placeholderTextColor={colors.hint}
                testID="io-text"
              />
            ) : null}
            <Text style={styles.hint}>
              Everything is stored only on this device. The cookie is sent to your server per request
              and never persisted there. Export includes accounts and cookies — treat it like a
              password.
            </Text>

            <View style={styles.actions}>
              <Pressable
                style={[styles.btn, styles.btnGhost]}
                onPress={() => onClose({ changed: false, reloadFeed: false })}
              >
                <Text style={styles.btnGhostText}>Cancel</Text>
              </Pressable>
              <Pressable style={styles.btn} onPress={save} testID="settings-save">
                <Text style={styles.btnText}>Save</Text>
              </Pressable>
            </View>
          </ScrollView>
        </View>
      </KeyboardAvoidingView>
    </View>
  );
}

const styles = StyleSheet.create({
  // Opaque page over the feed, tab bar stays visible below (web parity).
  page: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: colors.bg, zIndex: 20 },
  fill: { flex: 1 },
  inner: { flex: 1, width: '100%', maxWidth: 560, alignSelf: 'center' },
  content: { padding: 20, paddingBottom: 40 },
  title: { color: colors.text, fontSize: 20, fontWeight: '700', marginBottom: 4 },
  section: { color: colors.accent, fontSize: 13, fontWeight: '700', marginTop: 18, marginBottom: 6 },
  label: { color: colors.textDim, fontSize: 13, marginBottom: 5, marginTop: 8 },
  input: {
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: '#33333f',
    borderRadius: 10,
    color: colors.text,
    paddingHorizontal: 12,
    paddingVertical: 9,
    fontSize: 15,
  },
  cookieInput: { minHeight: 100, textAlignVertical: 'top', fontSize: 12 },
  numInput: { width: 80, textAlign: 'center', paddingVertical: 6 },
  mono: { fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace' },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 7,
    gap: 12,
  },
  rowLabel: { color: colors.text, fontSize: 14.5, flex: 1 },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: '#33333f',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  pickerText: { color: colors.text, fontSize: 15, flex: 1 },
  pickerChevron: { color: colors.hint },
  maskedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: '#33333f',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
  },
  maskedText: { color: colors.textDim, fontSize: 13, flex: 1 },
  smallBtn: {
    borderWidth: 1,
    borderColor: '#3a3a48',
    borderRadius: 999,
    paddingHorizontal: 13,
    paddingVertical: 6,
  },
  smallBtnText: { color: colors.textDim, fontSize: 13 },
  danger: { color: '#ff6b5e', fontSize: 13, marginTop: 10 },
  ioRow: { flexDirection: 'row', gap: 10, marginBottom: 10 },
  hint: { color: colors.hint, fontSize: 12, marginTop: 12, lineHeight: 17 },
  actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 18 },
  btn: { backgroundColor: colors.accent, borderRadius: 999, paddingHorizontal: 22, paddingVertical: 10 },
  btnText: { color: '#fff', fontWeight: '600' },
  btnGhost: { backgroundColor: 'transparent', borderWidth: 1, borderColor: '#33333f' },
  btnGhostText: { color: colors.textDim, fontWeight: '600' },
});

// frontend/src/components/SettingsPage.svelte
<script>
  import { tick } from 'svelte';
  import { Switch, Checkbox } from 'bits-ui';
  import {
    settings,
    saveSettings,
    activeCookie,
    replaceSettings,
    DEFAULTS,
  } from '../lib/settings.svelte.js';
  import { P, startFeed, showTab, settingsSaved } from '../lib/player.svelte.js';
  import { apiBase } from '../lib/api.js';
  import { showToast } from '../lib/toast.svelte.js';
  import { presentActionSheet } from '../lib/sheet.svelte.js';
  import Icon from './Icon.svelte';

  const TOGGLES = [
    { key: 'fillScreen', label: 'Fill screen (crop to fill)' },
    { key: 'vertical', label: 'Vertical navigation (swipe up/down)' },
    { key: 'smoothScroll', label: 'Smooth scrolling' },
    { key: 'showPauseIcon', label: 'Paused indicator on videos' },
    { key: 'moveBar', label: 'Movable progress bar (tap near an edge)' },
    { key: 'barInvert', label: 'Left/right progress bar fills upwards' },
    { key: 'skipSeen', label: "Skip posts you've already seen" },
    { key: 'debug', label: 'Debug overlay (audio + performance)' },
  ];
  const FILTERS = [
    { key: 'showImages', label: 'Images & galleries' },
    { key: 'showVideos', label: 'Videos' },
    { key: 'showText', label: 'Text posts' },
  ];

  // Which account the page is editing: an index into settings.accounts, or
  // -1 for the "add new account" entry.
  let editingAccount = $state(settings.accounts.length ? settings.activeAccount : -1);
  let accountName = $state('');
  let cookieValue = $state('');
  // The stored cookie is never shown on open — opening settings must not put
  // the credential on screen. A saved cookie renders as a masked row with a
  // Show button; the textarea (with the real value) appears only on demand.
  let cookieMasked = $state(false);
  let serverUrl = $state(settings.serverUrl);
  let imageSeconds = $state(settings.imageSeconds);
  let bools = $state(
    Object.fromEntries([...TOGGLES, ...FILTERS].map(({ key }) => [key, settings[key]]))
  );
  let ioVisible = $state(false);
  let ioValue = $state('');
  let ioEl = $state(null);

  function loadAccountFields() {
    const a = settings.accounts[editingAccount];
    accountName = a ? a.name : '';
    cookieValue = '';
    cookieMasked = !!a?.cookie;
  }
  loadAccountFields();

  const accountLabel = $derived.by(() => {
    if (editingAccount === -1) return '+ Add account…';
    const a = settings.accounts[editingAccount];
    return (
      (a?.name || `Account ${editingAccount + 1}`) +
      (editingAccount === settings.activeAccount ? ' (active)' : '')
    );
  });

  async function pickAccount() {
    const options = settings.accounts.map((a, i) => ({
      text: (a.name || `Account ${i + 1}`) + (i === settings.activeAccount ? ' (active)' : ''),
      value: String(i),
    }));
    options.push({ text: '+ Add account…', value: 'new' });
    const v = await presentActionSheet(
      'Account',
      options,
      editingAccount === -1 ? 'new' : String(editingAccount)
    );
    if (v === undefined) return;
    editingAccount = v === 'new' ? -1 : Number(v);
    loadAccountFields();
  }

  function revealCookie() {
    cookieValue = settings.accounts[editingAccount]?.cookie || '';
    cookieMasked = false;
  }

  function deleteAccount() {
    if (editingAccount < 0) return;
    settings.accounts.splice(editingAccount, 1);
    if (settings.activeAccount >= settings.accounts.length) settings.activeAccount = 0;
    editingAccount = settings.accounts.length
      ? Math.min(editingAccount, settings.accounts.length - 1)
      : -1;
    const prevCookie = settings.cookie;
    settings.cookie = activeCookie();
    saveSettings();
    loadAccountFields();
    showToast('Account deleted');
    if (prevCookie !== settings.cookie && P.feedActive) startFeed(P.feedPath);
  }

  function save() {
    const changed = (key) => settings[key] !== bools[key];
    const filtersChanged = ['showImages', 'showVideos', 'showText', 'skipSeen'].some(changed);
    const verticalChanged = changed('vertical');
    const prevCookie = settings.cookie;
    const prevServer = apiBase();

    // Saving selects the edited account as the active one.
    const name = accountName.trim();
    // A masked (hidden) cookie field means "unchanged": keep the stored value.
    // Once revealed, the field is authoritative — clearing it clears the cookie.
    const cookie = cookieMasked
      ? settings.accounts[editingAccount]?.cookie || ''
      : cookieValue.trim();
    if (editingAccount === -1) {
      if (name || cookie) {
        settings.accounts.push({ name: name || `Account ${settings.accounts.length + 1}`, cookie });
        settings.activeAccount = settings.accounts.length - 1;
      }
    } else if (settings.accounts[editingAccount]) {
      settings.accounts[editingAccount] = { name: name || `Account ${editingAccount + 1}`, cookie };
      settings.activeAccount = editingAccount;
    }
    settings.cookie = activeCookie();

    settings.serverUrl = String(serverUrl).trim();
    settings.imageSeconds = Math.max(1, parseFloat(imageSeconds) || DEFAULTS.imageSeconds);
    for (const key of Object.keys(bools)) settings[key] = bools[key];
    settingsSaved({ filtersChanged, verticalChanged, prevCookie, prevServer });
  }

  // -------------------------------------------------------------------------
  // Settings export/import: move accounts + preferences between devices,
  // since localStorage is per-browser.
  // -------------------------------------------------------------------------
  async function exportSettings() {
    const json = JSON.stringify($state.snapshot(settings), null, 1);
    ioVisible = true;
    ioValue = json;
    await tick();
    ioEl?.select?.();
    navigator.clipboard
      ?.writeText(json)
      .then(() => showToast('Settings copied to clipboard'))
      .catch(() => showToast('Copy the JSON from the box below'));
  }

  async function importSettings() {
    if (!ioVisible || !ioValue.trim()) {
      ioVisible = true;
      ioValue = '';
      await tick();
      ioEl?.focus();
      showToast('Paste exported JSON, then press Import again');
      return;
    }
    let parsed;
    try {
      parsed = JSON.parse(ioValue);
    } catch {
      showToast('That is not valid JSON');
      return;
    }
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
      showToast('That does not look like exported settings');
      return;
    }
    replaceSettings(parsed);
    // Refresh the form's local state from the imported settings.
    serverUrl = settings.serverUrl;
    imageSeconds = settings.imageSeconds;
    for (const key of Object.keys(bools)) bools[key] = settings[key];
    editingAccount = settings.accounts.length ? settings.activeAccount : -1;
    loadAccountFields();
    ioVisible = false;
    showToast('Settings imported');
    if (P.feedActive) startFeed(P.feedInput.trim());
  }

  // Tapping the row text toggles the control, like ion-toggle labels did.
  function rowToggle(e, key) {
    if (e.target.closest('[data-switch-root], [data-checkbox-root]')) return;
    bools[key] = !bools[key];
  }
</script>

<section id="settings-page">
  <form id="settings-form" onsubmit={(e) => e.preventDefault()}>
    <h2>Settings</h2>

    <div class="list">
      <div class="item">
        <span class="item-label">Account</span>
        <button type="button" class="pill account-pill" onclick={pickAccount}>{accountLabel}</button>
      </div>
      <div class="item">
        <label class="item-label" for="account-name-input">Account name</label>
        <input
          id="account-name-input"
          class="item-input"
          bind:value={accountName}
          placeholder="e.g. main"
          autocomplete="off"
        />
      </div>
      {#if cookieMasked}
        <div class="item">
          <span class="item-label"
            >Reddit cookie saved ({settings.accounts[editingAccount]?.cookie.length || 0} chars)</span
          >
          <button type="button" class="btn-outline" onclick={revealCookie}>
            <Icon name="eye-outline" /> Show
          </button>
        </div>
      {:else}
        <div class="item item-stacked">
          <label class="stacked-label" for="cookie-input">Reddit cookie</label>
          <textarea
            id="cookie-input"
            bind:value={cookieValue}
            rows="4"
            placeholder="Paste the FULL Cookie header from a logged-in reddit.com request (DevTools → Network → request headers). Just reddit_session usually gets blocked as a bot."
          ></textarea>
        </div>
      {/if}
      {#if editingAccount >= 0}
        <div class="item item-end">
          <button type="button" class="btn-danger" onclick={deleteAccount}>Delete this account</button>
        </div>
      {/if}
    </div>

    <div class="list">
      <div class="item item-stacked">
        <label class="stacked-label" for="server-url-input">Backend server URL</label>
        <input
          id="server-url-input"
          type="url"
          inputmode="url"
          autocomplete="off"
          autocapitalize="off"
          bind:value={serverUrl}
          placeholder="Empty = this server. Required in the iOS app, e.g. https://redditview.example.com"
        />
      </div>
      <div class="item">
        <label class="item-label" for="image-seconds-input">Image duration (seconds)</label>
        <input
          id="image-seconds-input"
          class="item-input num"
          type="number"
          min="1"
          max="600"
          step="0.5"
          bind:value={imageSeconds}
        />
      </div>
      {#each TOGGLES as t (t.key)}
        <!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions -->
        <div class="item item-toggle" onclick={(e) => rowToggle(e, t.key)}>
          <span class="item-label">{t.label}</span>
          <Switch.Root class="switch" bind:checked={bools[t.key]}>
            <Switch.Thumb class="switch-thumb" />
          </Switch.Root>
        </div>
      {/each}
    </div>

    <div class="list">
      <div class="list-header">Show post types</div>
      {#each FILTERS as f (f.key)}
        <!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions -->
        <div class="item item-toggle" onclick={(e) => rowToggle(e, f.key)}>
          <Checkbox.Root class="checkbox" bind:checked={bools[f.key]}>
            <svg class="checkbox-mark" viewBox="0 0 24 24" aria-hidden="true">
              <path
                d="M5 12.5l4.5 4.5L19 7.5"
                fill="none"
                stroke="currentColor"
                stroke-width="3"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          </Checkbox.Root>
          <span class="item-label">{f.label}</span>
        </div>
      {/each}
    </div>

    <div class="settings-io">
      <button type="button" class="btn-outline" onclick={exportSettings}>Export settings</button>
      <button type="button" class="btn-outline" onclick={importSettings}>Import settings</button>
    </div>
    {#if ioVisible}
      <textarea
        id="io-text"
        bind:this={ioEl}
        bind:value={ioValue}
        rows="3"
        placeholder="Exported settings JSON appears here — or paste JSON and press Import again"
      ></textarea>
    {/if}
    <p class="hint">
      Everything is stored only in this browser's localStorage. The cookie is sent to the backend
      per request and never persisted server-side. Export includes accounts and cookies — treat it
      like a password.
    </p>
    <div class="actions">
      <button type="button" class="btn-outline" onclick={() => showTab('posts')}>Cancel</button>
      <button type="button" class="btn-solid" onclick={save}>Save</button>
    </div>
  </form>
</section>
